-- MySQL Script generated by MySQL Workbench
-- Fri Oct 27 14:32:17 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TheatreAppSuite
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TheatreAppSuite
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TheatreAppSuite` DEFAULT CHARACTER SET utf8 ;
USE `TheatreAppSuite` ;

-- -----------------------------------------------------
-- Table `TheatreAppSuite`.`Play`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TheatreAppSuite`.`Play` (
  `PlayID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NULL,
  `FilePath` VARCHAR(100) NULL,
  PRIMARY KEY (`PlayID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheatreAppSuite`.`Line`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TheatreAppSuite`.`Line` (
  `LineID` INT NOT NULL AUTO_INCREMENT,
  `PlayID` INT NOT NULL,
  `ActNum` INT NOT NULL,
  `SceneNum` INT NOT NULL,
  `LineNum` INT NOT NULL,
  `Text` VARCHAR(500) NOT NULL,
  `DirectorNote` VARCHAR(500) NULL,
  PRIMARY KEY (`LineID`),
  INDEX `PlayID_idx` (`PlayID` ASC),
  CONSTRAINT `LinePlayID`
    FOREIGN KEY (`PlayID`)
    REFERENCES `TheatreAppSuite`.`Play` (`PlayID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheatreAppSuite`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TheatreAppSuite`.`User` (
  `UserID` INT NOT NULL,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheatreAppSuite`.`Permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TheatreAppSuite`.`Permissions` (
  `UserID` INT NOT NULL,
  `PlayID` INT NOT NULL,
  `Director` BIT NULL,
  `StageManager` BIT NULL,
  `AsstStageManager` BIT NULL,
  `Light` BIT NULL,
  `Sound` BIT NULL,
  `StageCrew` BIT NULL,
  `Actor` BIT NULL,
  INDEX `UserID_idx` (`UserID` ASC),
  INDEX `PlayID_idx` (`PlayID` ASC),
  CONSTRAINT `PermissionsUserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `TheatreAppSuite`.`User` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `PermissionsPlayID`
    FOREIGN KEY (`PlayID`)
    REFERENCES `TheatreAppSuite`.`Play` (`PlayID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheatreAppSuite`.`Character`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TheatreAppSuite`.`Character` (
  `CharacterID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(200) NULL,
  PRIMARY KEY (`CharacterID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheatreAppSuite`.`Blocking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TheatreAppSuite`.`Blocking` (
  `CharacterID` INT NOT NULL,
  `LineID` INT NOT NULL,
  `Origin` VARCHAR(10) NULL,
  `Destination` VARCHAR(10) NULL,
  `MovementType` VARCHAR(20) NULL,
  INDEX `CharacterID_idx` (`CharacterID` ASC),
  INDEX `LineID_idx` (`LineID` ASC),
  CONSTRAINT `BlockingCharacterID`
    FOREIGN KEY (`CharacterID`)
    REFERENCES `TheatreAppSuite`.`Character` (`CharacterID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `BlockingLineID`
    FOREIGN KEY (`LineID`)
    REFERENCES `TheatreAppSuite`.`Line` (`LineID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheatreAppSuite`.`Light`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TheatreAppSuite`.`Light` (
  `LightID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Type` VARCHAR(45) NULL,
  PRIMARY KEY (`LightID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheatreAppSuite`.`LightingCue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TheatreAppSuite`.`LightingCue` (
  `LightID` INT NOT NULL,
  `LineID` INT NOT NULL,
  `Location` VARCHAR(10) NOT NULL,
  `Status` VARCHAR(3) NULL,
  `UserID` INT NULL,
  INDEX `LightID_idx` (`LightID` ASC),
  INDEX `LineID_idx` (`LineID` ASC),
  INDEX `UserID_idx` (`UserID` ASC),
  CONSTRAINT `LightingCueLightID`
    FOREIGN KEY (`LightID`)
    REFERENCES `TheatreAppSuite`.`Light` (`LightID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `LightingCueLineID`
    FOREIGN KEY (`LineID`)
    REFERENCES `TheatreAppSuite`.`Line` (`LineID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `LightingCueUserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `TheatreAppSuite`.`User` (`UserID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheatreAppSuite`.`Prop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TheatreAppSuite`.`Prop` (
  `PropID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(200) NULL,
  PRIMARY KEY (`PropID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheatreAppSuite`.`PropMovement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TheatreAppSuite`.`PropMovement` (
  `PropID` INT NOT NULL,
  `LineID` INT NOT NULL,
  `UserID` INT NULL,
  `Location` VARCHAR(45) NULL,
  INDEX `PropID_idx` (`PropID` ASC),
  INDEX `LineID_idx` (`LineID` ASC),
  INDEX `UserID_idx` (`UserID` ASC),
  CONSTRAINT `PropMovementPropID`
    FOREIGN KEY (`PropID`)
    REFERENCES `TheatreAppSuite`.`Prop` (`PropID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `PropMovementLineID`
    FOREIGN KEY (`LineID`)
    REFERENCES `TheatreAppSuite`.`Line` (`LineID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `PropMovememntUserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `TheatreAppSuite`.`User` (`UserID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheatreAppSuite`.`Sound`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TheatreAppSuite`.`Sound` (
  `SoundID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(200) NULL,
  PRIMARY KEY (`SoundID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheatreAppSuite`.`SoundCue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TheatreAppSuite`.`SoundCue` (
  `SoundID` INT NOT NULL,
  `LineID` INT NOT NULL,
  `UserID` INT NULL,
  `Note` VARCHAR(200) NULL,
  INDEX `SoundID_idx` (`SoundID` ASC),
  INDEX `LineID_idx` (`LineID` ASC),
  INDEX `UserID_idx` (`UserID` ASC),
  CONSTRAINT `SoundCueSoundID`
    FOREIGN KEY (`SoundID`)
    REFERENCES `TheatreAppSuite`.`Sound` (`SoundID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `SoundCueLineID`
    FOREIGN KEY (`LineID`)
    REFERENCES `TheatreAppSuite`.`Line` (`LineID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `SoundCueUserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `TheatreAppSuite`.`User` (`UserID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheatreAppSuite`.`Costume`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TheatreAppSuite`.`Costume` (
  `CostumeID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(200) NULL,
  PRIMARY KEY (`CostumeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheatreAppSuite`.`CostumeCue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TheatreAppSuite`.`CostumeCue` (
  `CostumeID` INT NULL,
  `LineID` INT NULL,
  `CharacterID` INT NULL,
  `Note` VARCHAR(200) NULL,
  INDEX `CostumeID_idx` (`CostumeID` ASC),
  INDEX `LineID_idx` (`LineID` ASC),
  INDEX `CharacterID_idx` (`CharacterID` ASC),
  CONSTRAINT `CostumeCueCostumeID`
    FOREIGN KEY (`CostumeID`)
    REFERENCES `TheatreAppSuite`.`Costume` (`CostumeID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `CostumeCueLineID`
    FOREIGN KEY (`LineID`)
    REFERENCES `TheatreAppSuite`.`Line` (`LineID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `CostumeCueCharacterID`
    FOREIGN KEY (`CharacterID`)
    REFERENCES `TheatreAppSuite`.`Character` (`CharacterID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheatreAppSuite`.`CharacterUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TheatreAppSuite`.`CharacterUser` (
  `UserID` INT NOT NULL,
  `CharacterID` INT NOT NULL,
  INDEX `UserID_idx` (`UserID` ASC),
  INDEX `CharacterID_idx` (`CharacterID` ASC),
  CONSTRAINT `CUUserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `TheatreAppSuite`.`User` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `CUCharacterID`
    FOREIGN KEY (`CharacterID`)
    REFERENCES `TheatreAppSuite`.`Character` (`CharacterID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
